# Generated by Django 5.2.5 on 2025-10-31 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_emailotptelegramlink_telegramlinktoken"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("platform", models.CharField(max_length=20)),
                ("telegram_id", models.CharField(blank=True, max_length=64, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="created_via",
            field=models.CharField(
                blank=True,
                choices=[("web", "Web"), ("telegram", "Telegram")],
                default="web",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="login_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("telegram", "Telegram"),
                    ("both", "Both"),
                ],
                default="email",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_linked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_photo_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["telegram_id"], name="account_use_telegra_6f34c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["login_method"], name="account_use_login_m_42ecca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="account_use_email_553b8f_idx"),
        ),
        migrations.AddField(
            model_name="authauditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auth_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="authauditlog",
            index=models.Index(
                fields=["user_id"], name="account_aut_user_id_c9f7cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authauditlog",
            index=models.Index(
                fields=["created_at"], name="account_aut_created_83ce19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authauditlog",
            index=models.Index(
                fields=["action", "platform"], name="account_aut_action_6c2aad_idx"
            ),
        ),
    ]
