# Generated by Django 5.2.5 on 2025-11-03 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_authauditlog_user_created_via_user_last_login_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailotptelegramlink",
            name="code",
        ),
        migrations.AddField(
            model_name="emailotptelegramlink",
            name="code_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="emailotptelegramlink",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="emailotptelegramlink",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_otp_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="emailotptelegramlink",
            index=models.Index(
                fields=["email", "expires_at"], name="account_ema_email_cc2496_idx"
            ),
        ),
    ]
