# Generated by Django 5.2.5 on 2025-11-04 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_add_miniapp_email_connection_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramLinkNonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nonce",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "telegram_user_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_link_nonces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["nonce", "used"], name="account_tel_nonce_bce663_idx"
                    ),
                    models.Index(
                        fields=["user", "expires_at"],
                        name="account_tel_user_id_19ff95_idx",
                    ),
                ],
            },
        ),
    ]
