# Generated by Django 5.2.1 on 2025-06-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="tags",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="preparation",
            field=models.CharField(
                blank=True,
                help_text="Optional: large, grated, cubed, etc.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
