# Generated by Django 5.2.1 on 2025-07-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='subscription_plan',
            field=models.CharField(choices=[('standard', 'Standard'), ('healthy', 'Healthy'), ('premium', 'Premium')], default='standard', help_text='Required subscription tier', max_length=20),
        ),
    ]
