# Generated by Django 5.2.1 on 2025-07-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_subscription_plan'),
        ('recipes', '0011_default_mealtypes'),
    ]

    operations = [
    ]
