# Generated by Django 5.2.1 on 2025-08-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_default_mealtypes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="amount",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
