# Generated by Django 5.2.1 on 2025-08-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_ingredient_amount'),
        ('recipes', '0012_merge_20250731_1833'),
    ]

    operations = [
    ]
