# Generated by Django 5.2.1 on 2025-08-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0013_merge_20250802_1302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglistitem",
            name="amount",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="shoppinglistitem",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
