# Generated by Django 5.2.1 on 2025-08-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0014_alter_shoppinglistitem_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="source",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="recipe",
            name="source_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="recipe",
            unique_together={("source", "source_id")},
        ),
    ]
