# Generated by Django 5.2.1 on 2025-08-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0015_recipesubmission_recipesubmissionimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipesubmission",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="recipesubmission",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="recipesubmission",
            name="tags",
        ),
        migrations.AddField(
            model_name="recipesubmission",
            name="calories",
            field=models.PositiveIntegerField(
                blank=True, help_text="Calories in kcal (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="recipesubmission",
            name="carbs",
            field=models.PositiveIntegerField(
                blank=True, help_text="Carbs in grams (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="recipesubmission",
            name="categories",
            field=models.ManyToManyField(blank=True, to="recipes.category"),
        ),
        migrations.AddField(
            model_name="recipesubmission",
            name="cook_time",
            field=models.PositiveIntegerField(default=1, help_text="in minutes"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipesubmission",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipesubmission",
            name="description_ru",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="recipesubmission",
            name="description_uz",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="recipesubmission",
            name="fats",
            field=models.PositiveIntegerField(
                blank=True, help_text="Fats in grams (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="recipesubmission",
            name="healthy",
            field=models.BooleanField(
                default=False, help_text="Show as Healthy Recipe"
            ),
        ),
        migrations.AddField(
            model_name="recipesubmission",
            name="name_ru",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="recipesubmission",
            name="name_uz",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="recipesubmission",
            name="prep_time",
            field=models.PositiveIntegerField(default=1, help_text="in minutes"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipesubmission",
            name="protein",
            field=models.PositiveIntegerField(
                blank=True, help_text="Protein in grams (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="recipesubmission",
            name="servings",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipesubmission",
            name="subscription_plan",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("healthy", "Healthy"),
                    ("premium", "Premium"),
                ],
                default="standard",
                help_text="Required subscription tier",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cook_time",
            field=models.PositiveIntegerField(default=1, help_text="in minutes"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="prep_time",
            field=models.PositiveIntegerField(default=1, help_text="in minutes"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="recipesubmission",
            name="ingredients",
            field=models.JSONField(default=list, help_text="List of ingredient dicts"),
        ),
        migrations.AlterField(
            model_name="recipesubmission",
            name="steps",
            field=models.JSONField(default=list, help_text="List of step dicts"),
        ),
    ]
