# Generated by Django 5.2.1 on 2025-08-19 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_userrecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
    ]
