# Generated by Django 5.2.6 on 2025-09-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0018_alter_recipe_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="unit_ru",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="unit_uz",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
