# Generated by Django 5.2.1 on 2025-09-15 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_author_user_author"),
        ("recipes", "0019_ingredient_unit_ru_ingredient_unit_uz"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipes",
                to="account.author",
            ),
        ),
    ]
