# Generated by Django 5.2.1 on 2025-09-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0021_recipesubmission_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipesubmission",
            name="cook_time",
            field=models.PositiveIntegerField(
                blank=True, help_text="in minutes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipesubmission",
            name="prep_time",
            field=models.PositiveIntegerField(
                blank=True, help_text="in minutes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipesubmission",
            name="servings",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
